export enum SearchActionTypes {
  SEARCH_PRODUCTS = 'SEARCH_PRODUCTS',
  SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS',
  SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR',
  SEARCH_PRODUCTS_NEXT_PAGE = 'SEARCH_PRODUCTS_NEXT_PAGE',
  SEARCH_PRODUCTS_NEXT_PAGE_SUCCESS = 'SEARCH_PRODUCTS_NEXT_PAGE_SUCCESS',
  SEARCH_PRODUCTS_NEXT_PAGE_ERROR = 'SEARCH_PRODUCTS_NEXT_PAGE_ERROR',
}
