enum Routes {
  HomeScreen = 'HomeScreen',
  HomeTabScreen = 'HomeTabScreen',
  MapScreen = 'MapScreen',
  SignUp = 'SignUp',
  SignUpOTP = 'SignUpOTP',
  SignUpOTPVerification = 'SignUpOTPVerification',
  CreatePassword = 'CreatePassword',
  TabNavigation = 'TabNavigation',
  ConfirmAddress = 'ConfirmAddress',
  Checkout = 'Checkout',
  ProductsScreen = 'ProductsScreen',
  Onboard = 'Onboard',
  Login = 'Login',
  Basket = 'Basket',
  OrderConfirmation = 'OrderConfirmation',
  ResetPassword = 'ResetPassword',
  CheckEmail = 'CheckEmail',
  UpdatePassword = 'UpdatePassword',
  ResetPasswordSuccess = 'ResetPasswordSuccess',
  DrawerNavigation = 'DrawerNavigation',
  OrderList = 'OrderList',
  OrderDetails = 'OrderDetails',
  Search = 'Search',
}

export default Routes;
