name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - run: yarn run lint
      - run: yarn global add detox-cli
      - run: yarn global add react-native-cli
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn run e2e:ios
